/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <AppKit/NSWindow.h>

@class NSDrawer;

@interface NSDrawerWindow : NSWindow
{
    NSDrawer *_drawer;
    NSWindow *_drawerParentWindow;
}

+ (Class)frameViewClassForStyleMask:(unsigned int)fp8;
- (id)initWithContentRect:(struct _NSRect)fp8 styleMask:(unsigned int)fp24 backing:(int)fp28 defer:(BOOL)fp32 drawer:(id)fp36;
- (void)_changeTexture;
- (void)_setParentWindow:(id)fp8;
- (id)_parentWindow;
- (struct _NSSize)_potentialMinSize;
- (struct _NSSize)_potentialMaxSize;
- (struct _NSSize)minSize;
- (struct _NSSize)maxSize;
- (BOOL)hasShadow;
- (void)_changeKeyAndMainLimitedOK:(BOOL)fp8;
- (BOOL)isKeyWindow;
- (BOOL)canBecomeKeyWindow;
- (void)becomeKeyWindow;
- (void)_drawerTakeFocus;
- (void)makeKeyWindow;
- (void)resignKeyWindow;
- (void)_changeDrawerKeyState;
- (void)_changeDrawerMainState;
- (void)_changeDrawerFirstResponder;
- (id)_generateScaledBackground;
- (id)_compositedBackground;
- (BOOL)_useMetalPattern;
- (void)_resetDrawerFirstResponder;
- (void)orderOut:(id)fp8;
- (BOOL)isMainWindow;
- (BOOL)canBecomeMainWindow;
- (void)becomeMainWindow;
- (void)makeMainWindow;
- (void)resignMainWindow;
- (BOOL)_hasActiveControls;
- (void)_setForceActiveControls:(BOOL)fp8;
- (BOOL)worksWhenModal;
- (id)_getUndoManager:(BOOL)fp8;
- (BOOL)isExcludedFromWindowsMenu;
- (id)fieldEditor:(BOOL)fp8 forObject:(id)fp12;
- (void)_resetFirstResponder;
- (BOOL)makeFirstResponder:(id)fp8;
- (id)_newFirstResponderAfterResigning;
- (id)_oldFirstResponderBeforeBecoming;
- (void)_selectFirstKeyView;
- (void)resizeWithDelta:(struct _NSPoint)fp8 fromFrame:(struct _NSRect)fp16 beginOperation:(BOOL)fp32 endOperation:(BOOL)fp36;
- (BOOL)_isVertical;
- (BOOL)validateMenuItem:(id)fp8;
- (void)showToolbar:(id)fp8;
- (void)hideToolbar:(id)fp8;
- (void)toggleToolbarShown:(id)fp8;
- (void)runToolbarCustomizationPalette:(id)fp8;
- (void)performClose:(id)fp8;
- (void)performZoom:(id)fp8;
- (void)performMiniaturize:(id)fp8;
- (void)_adjustWindowToScreen;
- (BOOL)isMovableByWindowBackground;
- (void)_cycleDrawersReversed:(BOOL)fp8;
- (BOOL)performKeyEquivalent:(id)fp8;

@end

