/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <NSFrameView.h>

@class NSColor;

@interface NSDrawerFrame : NSFrameView
{
    NSColor *drawerBackground;
    int trackingTag;
    int drawerEdge;
    BOOL registeredForEdgeChanges;
}

+ (void)initialize;
+ (struct _NSRect)frameRectForContentRect:(struct _NSRect)fp8 styleMask:(unsigned int)fp24;
+ (struct _NSRect)contentRectForFrameRect:(struct _NSRect)fp8 styleMask:(unsigned int)fp24;
+ (struct _NSSize)minFrameSizeForMinContentSize:(struct _NSSize)fp8 styleMask:(unsigned int)fp16;
+ (struct _NSSize)minContentSizeForMinFrameSize:(struct _NSSize)fp8 styleMask:(unsigned int)fp16;
+ (float)minFrameWidthWithTitle:(id)fp8 styleMask:(unsigned int)fp12;
- (BOOL)isOpaque;
- (id)initWithFrame:(struct _NSRect)fp8 styleMask:(unsigned int)fp24 owner:(id)fp28;
- (void)registerForEdgeChanges:(id)fp8;
- (void)shapeWindow;
- (struct _NSSize)minFrameSize;
- (struct _NSRect)contentRect;
- (void)setFrameSize:(struct _NSSize)fp8;
- (void)drawBevel:(struct _NSRect)fp8;
- (void)_drawIndicatorInRect:(struct _NSRect)fp8;
- (struct _NSRect)resizeIndicatorRect;
- (void)drawResizeIndicator:(struct _NSRect)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (void)drawFrame:(struct _NSRect)fp8;
- (void)_drawFrameRects:(struct _NSRect)fp8;
- (id)contentFill;
- (void)adjustHalftonePhase;
- (BOOL)acceptsFirstMouse:(id)fp8;
- (void)_addTrackingRects;
- (void)_removeTrackingRects;
- (void)drawerDidOpen:(id)fp8;
- (void)drawerDidClose:(id)fp8;
- (void)resizeWithEvent:(id)fp8;
- (void)mouseDown:(id)fp8;
- (void)mouseEntered:(id)fp8;
- (void)mouseExited:(id)fp8;
- (void)viewWillMoveToWindow:(id)fp8;
- (void)viewDidMoveToWindow:(id)fp8;
- (void)_postFrameChangeNotification;
- (BOOL)shouldBeTreatedAsInkEvent:(id)fp8;
- (void)dealloc;
- (void)finalize;

@end

